### PR TITLE
Added German translation

### PR DESCRIPTION
**Pull request by scherii**
Hi @nikolov-tmw!

Great plugin! It's awesome that someone finally is developing an alternative to qTranslate.
Thank you for all your work. I want to help you and to begin with I translated the plugin in German. I am from Switzerland so there can be «errors» like the absence of ß (in Switzerland we don't use this letter, instead there will be «ss») and our quotation marks are « and » (instead of the „ and the “).

I've seen some errors at the original language-strings which I'll review as soon as I can.

Again, thanks for your work!

### CODE REVIEW

**Comment by nikolov-tmw** [comment]
Hi @scherii! 

Thank you for your contribution - it's highly appreciated. I was away for the past two weeks and that's what took me so long to merge the pull request. 

Feel free to fix anything else you've noticed. 

Nikola

**Comment by scherii** [comment]
Yup, I will. As soon as I figure out how I'll do that :smile:

Thanks for merging!

**Comment by scherii** [comment]
There is a problem with the translated version. If the German language file is active certain menus stop working. I'm a little bit short on time – so just ask if you need more information :)

EDIT: Should this go into a new issue?

**Comment by nikolov-tmw** [comment]
When I start working on the plugin again, I'll take a look into that. The
issue sounds familiar, but I'm not sure where it comes from.

**Pull request merged**
